- 👋 Hi, I’m Janhavi Jayanagarkar
- 👀 I’m interested in Statistics.
- 🌱 I’m currently learning..SAS,Clinical Trials,Quality Control,Python
- 📫 How to reach me @www.linkedin.com/in/janhavi-jayanagarkar-b65067240
